name: Security Vulnerability Report
description: Report a security vulnerability in dependencies or code
title: '[SECURITY] '
labels: ['security', 'vulnerability', 'requires-review']
assignees: ['security-team']

body:
  - type: markdown
    attributes:
      value: |
        ## 🔒 Security Vulnerability Report

        Thank you for reporting a security vulnerability. Please provide detailed information to help us assess and address the issue quickly.

        **⚠️ IMPORTANT:** For critical vulnerabilities, consider contacting the security team directly before filing this public issue.

  - type: input
    id: vulnerability-title
    attributes:
      label: Vulnerability Summary
      description: Provide a brief, descriptive title for this vulnerability
      placeholder: e.g., "Cross-site scripting in price conversion feature"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: Select the severity level based on impact and exploitability
      options:
        - Critical (9.0-10.0) - Immediate threat, exploitable remotely
        - High (7.0-8.9) - Significant impact, likely exploitable
        - Medium (4.0-6.9) - Moderate impact, some conditions required
        - Low (0.1-3.9) - Minimal impact, difficult to exploit
        - Unknown - Unable to determine severity
    validations:
      required: true

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: Select the primary vulnerability category
      options:
        - Dependency Vulnerability (npm package)
        - Cross-Site Scripting (XSS)
        - Injection (SQL, Command, etc.)
        - Authentication/Authorization
        - Data Exposure/Privacy
        - Denial of Service (DoS)
        - Other/Unknown
    validations:
      required: true

  - type: input
    id: affected-package
    attributes:
      label: Affected Package/Component
      description: Name of the dependency, file, or component affected
      placeholder: e.g., "lodash@4.17.20" or "src/content/priceFinder.js"
    validations:
      required: true

  - type: input
    id: cve-id
    attributes:
      label: CVE ID (if known)
      description: Official CVE identifier if this is a known vulnerability
      placeholder: e.g., "CVE-2023-12345"
    validations:
      required: false

  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: Detailed description of the vulnerability and its potential impact
      placeholder: |
        Describe:
        - What the vulnerability is
        - How it could be exploited
        - What data/systems could be affected
        - Potential business impact
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce/Discover
      description: Detailed steps to reproduce or discover this vulnerability
      placeholder: |
        1. Go to...
        2. Enter malicious input...
        3. Observe the result...
    validations:
      required: true

  - type: textarea
    id: proof-of-concept
    attributes:
      label: Proof of Concept
      description: Code, screenshots, or other evidence demonstrating the vulnerability
      placeholder: |
        Provide:
        - Code snippets
        - Screenshots
        - Network requests/responses
        - Error messages
    validations:
      required: false

  - type: textarea
    id: suggested-mitigation
    attributes:
      label: Suggested Mitigation
      description: Your recommendations for fixing or mitigating this vulnerability
      placeholder: |
        Suggest:
        - Immediate workarounds
        - Long-term fixes
        - Security controls
        - Package updates
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information about this vulnerability
      placeholder: |
        Include:
        - Related vulnerabilities
        - External references
        - Timeline constraints
        - Disclosure timeline
    validations:
      required: false

  - type: input
    id: reporter-contact
    attributes:
      label: Contact Information (Optional)
      description: Email or other contact method for follow-up questions
      placeholder: security@example.com
    validations:
      required: false

  - type: checkboxes
    id: confirmation
    attributes:
      label: Reporting Guidelines
      description: Please confirm you understand our security reporting process
      options:
        - label: I have verified this is a genuine security vulnerability
          required: true
        - label: I understand this issue will be handled according to our security response procedures
          required: true
        - label: I have not disclosed this vulnerability publicly before reporting it here
          required: true
        - label: I am willing to provide additional information if needed during investigation
          required: false

  - type: markdown
    attributes:
      value: |
        ## Next Steps

        After submitting this report:

        1. **Acknowledgment**: We will acknowledge receipt within 24 hours
        2. **Assessment**: Our security team will assess the vulnerability within 48 hours
        3. **Response**: We will provide an initial response with timeline within 72 hours
        4. **Resolution**: Critical/High severity issues will be prioritized for immediate fixing

        Thank you for helping keep our users and systems secure! 🛡️